apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-log4j
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  {{- (.Files.Glob "files/log4j2.xml").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}-properties
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 2 }}
<<<<<<< HEAD
    pack.enabled={{ .Values.cluster.enabled }}
=======
    pack.enabled={{ if (eq (.Values.replicaCount | int) 1) }} false {{ else }} true {{ end }}
>>>>>>> Enable pack if stardog replica count not 1
    pack.zookeeper.address={{ if .Values.zookeeper.enabled }} {{- template "zkservers" . }} {{ else }} {{ .Values.zookeeper.addresses }} {{ end }}
    pack.node.join.retry.count=15
    pack.node.join.retry.delay=1m
