apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stardog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

data:
  {{- (.Files.Glob "files/log4j2.xml").AsConfig | nindent 2 }}

  {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 2 }}
    pack.enabled={{ .Values.cluster.enabled }}
    pack.zookeeper.address={{ if .Values.zookeeper.enabled }} {{- template "zkservers" . }} {{ else }} {{ .Values.zookeeper.addresses }} {{ end }}
    pack.node.join.retry.count=15
    pack.node.join.retry.delay=1m
